### ISSUE TITLE
Missing dependency in requirements.txt

### ISSUE THREAD

**Issue by oew1v07** [alexwlchan/docstore#146]
Really liking this piece of work! However when I got to trying out

`docstore serve`

it failed with the following error

`ModuleNotFoundError: No module named 'hyperlink'`

I indeed found that hyperlink was not installed and therefore wasn't in the `requirements.txt`.

Have created fork to rectify and will PR soon

**Comment by alexwlchan** [comment]
Thanks for flagging! I recently pushed a new requirements.txt, so I think this is fixed.
